export declare const BASE_FILE = "rv.config";
export declare const RENDER_FN = "__vue_render__";
export declare const STATIC_RENDER_FN = "__vue_staticRenderFns__";
export declare const getSourceDir: <T = string>(path: string) => T;
export declare const ROOT_DIR: string;
export declare const SRC_DIR: string;
export declare const DIST_DIR: string;
export declare const ESM_SRC_DIR: string;
export declare const ESM_DIST_DIR: string;
export declare const CJS_SRC_DIR: string;
export declare const CJS_DIST_DIR: string;
export declare const UMD_SRC_DIR: string;
export declare const UMD_DIST_DIR: string;
export declare const AMD_SRC_DIR: string;
export declare const AMD_DIST_DIR: string;
